"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import NavBar from "@/component/Navbar";
import { store } from './_lib/store'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <head>

      <link
        rel="stylesheet"
        type="text/css"
        charSet="UTF-8"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
      />
      </head>
      <body className={inter.className}>
        <Provider store={store}>
        <ChakraProvider>
          <NavBar/>
          {/* <script src="https://www.google.com/recaptcha/api.js?render=reCAPTCHA_site_key"></script> */}
          {children} 
        </ChakraProvider>
        </Provider>
      </body>
    </html>
  );
}
