---
version: '3'
services:
  ### Postgres config ###
  postgres-order:
    container_name: postgres-order
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: unless-stopped


##########################################################
  ### Eureka Server ###
  discovery-server:
    container_name: discovery-server
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: unless-stopped
#    depends_on:

  ### API Gateway ###
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - discovery-server

  ### Order Service ###
  order-service:
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-order:5431/order-service
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - discovery-server
      - postgres-order
      - api-gateway